version: "3"
services:

  frontend:
    build: ./frontend
    environment:
      - BACKEND_URI_PREFIX="http://backend:8081"
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - yarn-cache:/root/yarn-cache

  backend:
    build: ./backend
    environment:
      - MONGO_URL=mongodb://mongo:27017/cinematickets
    ports:
      - "${BACKEND_PORT}:8081"
    volumes:
      - yarn-cache:/root/yarn-cache
    depends_on:
      - "mongo"

  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  yarn-cache:
